server:
  port: 9000
spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
    bootstrap-servers: 192.168.1.99:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  ####
  datasource:
    url: jdbc:mysql://106.55.181.141:3306/linsir-abc-kafka?characterEncoding=utf8
    username: root
    password: yu@2023
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
