# 应用配置
spring:
  application:
    name: linsir-abc-mongodb
  # MongoDB配置
  data:
    mongodb:
      uri: mongodb://localhost:27017/linsir-abc-mongodb
      database: linsir-abc-mongodb

# 服务器配置
server:
  port: 6080
