server:
  port: 10086

spring:
  datasource:
    url: jdbc:mysql://106.55.181.141:3306/linsir_subject_sms_v2?characterEncoding=utf8
    username: root
    password: yu@2023
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.linsir.subject.smsv2.entity
  mapper-locations: classpath:mapper/*.xml