server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/linsir-abc-redis?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    redis:
      namespace: spring:redis