server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://106.55.181.141:3306/linsir-abc-redis?characterEncoding=utf8
    username: root
    password: yu@2023
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    redis:
      namespace: spring:redis